# Generated by Django 5.0.7 on 2024-08-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='image',
        ),
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название сумки'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='BagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/bag_images', verbose_name='Фотографии сумки')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.bag')),
            ],
        ),
    ]
