# Generated by Django 5.0.7 on 2024-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
